### ISSUE TITLE
[+] Upload artifact only uploads `tar.xz`

### ISSUE THREAD

**Issue by Azathothas** [leleliu008/ppkg-package-manually-build#1]
Currently, the archive supported are:
```yaml
      pack-type:
        description: choose a pack type
        type: choice
        options:
          - tar.xz
          - tar.lz
          - tar.gz
          - tar.bz2
          - zip
```

But the artifact uploader has hard-coded `.tar.xz` format
```yaml
- uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}---linux-${{ github.event.inputs.target-arch }}.tar.xz
          path: ${{ github.event.inputs.package-name }}-*-linux*${{ github.event.inputs.target-arch }}.tar.xz
```

So if a user specifies any other format, the artifact doesn't get uploaded
Ref: https://github.com/Azathothas/ppkg-package-manually-build/actions/runs/10809905330/job/29985997665
